# Generated by Django 3.2.25 on 2025-06-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('product_image', models.JSONField()),
                ('status', models.CharField(choices=[('IN', 'In Stock'), ('OUT', 'Out of Stock'), ('LOW', 'Low Stock'), ('DISC', 'Discontinued')], default='IN', max_length=4)),
                ('category', models.IntegerField(choices=[(1, 'Vitamins'), (2, 'Supplements'), (3, 'Proteins'), (4, 'Medicine')], default=1)),
                ('count', models.IntegerField(choices=[(10, '10 count'), (30, '30 count'), (90, '90 count'), (120, '120 count'), (180, '180 count'), (240, '240 count'), (300, '300 count')], default=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heavenlyvitamin.user')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='heavenlyvitamin.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heavenlyvitamin.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
